import java.util.ArrayList;
ArrayList<String> boodschappen = new ArrayList<String>();
boodschappen.add("melk");
boodschappen.add("brood");
boodschappen.add("kaas");
boodschappen.add("druif");
boodschappen.add("kip");
println(boodschappen.get(1));
boodschappen.remove(0);
println(boodschappen.size());
